links:
  parent:
    optional: false
    auto: false
    role: node
    argname: node
  consume:
    - auto: false
      min: 0
      max: 1
      role: container
      argname: container
    - auto: false
      min: 0
      max: 1000
      role: influxdb
      argname: influxdb
